version: '3'

services:
  storybook:
    build: .
    volumes:
      - ./:/usr/src/app
    command: yarn storybook
    ports:
      - 6006:6006
    tty: true
    environment:
      - NODE_ENV=development
